DELETE FROM dbo.Submissions;

INSERT INTO dbo.Submissions (Id, NameRu, NameEn)
VALUES
    (1,  N'Рычаг локтя',                N'Armbar'),
    (2,  N'Обратный треугольник',       N'Reverse triangle'),
    (3,  N'Обратный рычаг локтя',       N'Reverse armbar'),
    (4,  N'Американа',                  N'Americana'),
    (5,  N'Кимура',                     N'Kimura'),
    (6,  N'Омо плата',                  N'Omoplata'),
    (7,  N'Барата плата',               N'Baratoplata'),
    (8,  N'Вирст лок',                  N'Wristlock'),
    (9,  N'Бицепс-слайсер',             N'Biceps slicer'),
    (10, N'Моноплата',                  N'Monoplata'),
    (11, N'Распятье',                   N'Crucifix'),
    (12, N'Прямой ахилл',               N'Straight ankle lock'),
    (13, N'Скрутка пятки (хилхук)',     N'Heel hook'),
    (14, N'Футлок',                     N'Footlock'),
    (15, N'Рычаг колена',               N'Kneebar'),
    (16, N'Калф-слайсер',               N'Calf slicer'),
    (17, N'Твистер',                    N'Twister'),
    (18, N'Банана-сплит',               N'Banana split'),
    (19, N'Эстима-лок',                 N'Estima lock'),
    (20, N'Треугольник',                N'Triangle choke'),
    (21, N'Гильотина',                  N'Guillotine choke'),
    (22, N'Кросс чок',                  N'Cross collar choke'),
    (23, N'Удушение сзади',             N'Rear naked choke'),
    (24, N'Лук и стрелы',               N'Bow and arrow choke'),
    (25, N'Удушение Иезекииля',         N'Ezekiel choke'),
    (26, N'Дарс-чок',                   N'D''Arce choke'),
    (27, N'Анаконда',                   N'Anaconda choke'),
    (28, N'Луп чок',                    N'Loop choke'),
    (29, N'Север-юг',                   N'North-south choke'),
    (30, N'Бейсбол чок',                N'Baseball choke'),
    (31, N'Джокер-чок',                 N'Joker choke');
